apiVersion: v1
kind: Service

metadata:
  name: ai-devsecops-service

spec:
  selector:
    app: ai-devsecops-template

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

  type: NodePort